# slack-notification-defaults: &SLACK_NOTIFICATION_DEFAULTS
#   channel: '#cloud-platform-notify'
#   silent: true
# slack-attachments-defaults: &SLACK_ATTACHMENTS_DEFAULTS
#   fallback: 'Finished building $BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
#   title: '$BUILD_TEAM_NAME/$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME#$BUILD_NAME'
#   title_link: 'https://concourse.cloud-platform.service.justice.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME'
#   footer: concourse.cloud-platform.service.justice.gov.uk

resources:
  - name: ((namespace))-repo
    type: git
    source:
      uri: ((repo-url))
      branch: master
      # git_crypt_key: ((repo-url))
  - name: tools-image
    type: docker-image
    source:
      repository: ministryofjustice/cloud-platform-tools
      tag: 1.1
  # - name: slack-alert
  #   type: slack-notification
  #   source:
  #     url: https://hooks.slack.com/services/((slack-hook-id))
  - name: every-30m
    type: time
    source:
      interval: 30m

resource_types:
# - name: slack-notification
#   type: docker-image
#   source:
#     repository: cfcommunity/slack-notification-resource
#     tag: latest

groups:
  - name: template-gitops
    jobs: [namespace-gitops]

jobs:
  - name: namespace-gitops
    serial: true
    plan:
      - aggregate:
          - get: every-30m
            trigger: true
          - get: ((namespace))-repo
            trigger: true
          - get: tools-image
      - task: apply-environments
        image: tools-image
        config:
          platform: linux
          inputs:
            - name: ((namespace))-repo
          params:
            AWS_ACCESS_KEY_ID: ((aws-pk-test-9.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws-pk-test-9.secret-access-key))
            TF_PLUGIN_CACHE_DIR: /tmp/terraform-plugin-cache
            KUBECONFIG: /tmp/kubeconfig
            # the variables prefixed with PIPELINE_ are used by the apply script
            PIPELINE_CLUSTER: pk-test-9.cloud-platform.service.justice.gov.uk
            KUBECONFIG: /tmp/kubeconfig
            PIPELINE_STATE_REGION: "eu-west-1"
            NAMESPACE: ((namespace))
          run:
            path: /bin/sh
            dir: ((namespace))-repo
            args:
              - -c
              - |
                mkdir -p "${TF_PLUGIN_CACHE_DIR}"
                aws s3 cp s3://cloud-platform-pk-test-9-kubecfg/kubeconfig-${NAMESPACE} /tmp/kubeconfig
                export KUBECONFIG=${KUBECONFIG}
                kubectl config use-context ${PIPELINE_CLUSTER}
                kubectl get secrets -n ${NAMESPACE}
                chmod +x ./gitops-deploy
                ./gitops-deploy
        on_failure:
          # put: slack-alert
          # params:
          #   <<: *SLACK_NOTIFICATION_DEFAULTS
          #   attachments:
          #     - color: "danger"
          #       <<: *SLACK_ATTACHMENTS_DEFAULTS
